package frontend.Instructor;

import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JLabel;

import backend.models.*;
import backend.databaseManager.*;

/**
 *
 * @author pc
 */
public class CourseEditor extends javax.swing.JDialog {

        private String mode;
        private String courseId;
        private Course course;
        private String instructorId;
        private Instructor instructor;
        private CourseDatabaseManager Cdb;
        private UsersDatabaseManager Udb;
        private InstructorDashboard parentView;

        /**
         * Creates new form CourseEditor
         */
        public CourseEditor(String instructorId, InstructorDashboard parent) {
                super(parent, "Dialog", true);
                this.parentView = parent; // Store reference to parent
                this.mode = "create";
                Cdb = new CourseDatabaseManager();
                Udb = new UsersDatabaseManager();
                this.courseId = Cdb.generateId();
                course = new Course(courseId, "", instructorId, "");
                initComponents();
                try {
                        advancedIntialize();
                } catch (Exception e) {
                        e.printStackTrace();
                }
        }

        public CourseEditor(String courseId, String instructorId, InstructorDashboard parent) {
                super(parent, "Dialog", true);
                this.parentView = parent; // Store reference to parent
                this.mode = "Edit";
                Cdb = new CourseDatabaseManager();
                Udb = new UsersDatabaseManager();
                this.courseId = courseId;
                this.instructorId = instructorId;
                instructor = (Instructor) Udb.getUser(instructorId);
                course = Cdb.getCourse(courseId);
                if (course == null) {
                        System.out.println("course with this id not found");
                }
                initComponents();
                try {
                        advancedIntialize();
                } catch (Exception e) {
                        e.printStackTrace();
                }
        }

        private void advancedIntialize() {
                this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                this.setLocationRelativeTo(null);
                String title;
                String description;
                if (mode.equalsIgnoreCase("create")) {
                        title = "";
                        description = "";
                        LblInstructorInfo.setText("");
                        // Name of label is not meaningful , but irrelevant here
                        jLabel1.setText("Create Course");
                } else {
                        title = course.getTitle();
                        description = course.getDescription();
                        // Name of label is not meaningful , but irrelevant here
                        LblInstructorInfo.setText("Course: " + title + " (ID: " + courseId + ")");
                }
                titleField.setText(title);
                describtionField.setText(description);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                LblInstructorInfo = new javax.swing.JLabel();
                btnReturn = new javax.swing.JButton();
                btnSave = new javax.swing.JButton();
                titleField = new javax.swing.JTextField();
                LblInstructorInfo1 = new javax.swing.JLabel();
                LblInstructorInfo3 = new javax.swing.JLabel();
                describtionField = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setResizable(false);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setText("Course Edit");
                jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
                jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                LblInstructorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                LblInstructorInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                LblInstructorInfo.setText("jLabel2");
                LblInstructorInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                LblInstructorInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnReturn.setText("Return");
                btnReturn.setToolTipText("");
                btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                btnReturn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
                btnReturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnReturn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReturnActionPerformed(evt);
                        }
                });

                btnSave.setBackground(new java.awt.Color(0, 204, 0));
                btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                btnSave.setForeground(new java.awt.Color(255, 255, 255));
                btnSave.setText("Save");
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                titleField.setText("jTextField1");

                LblInstructorInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                LblInstructorInfo1.setText("Title");
                LblInstructorInfo1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                LblInstructorInfo1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                LblInstructorInfo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                LblInstructorInfo3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                LblInstructorInfo3.setText("Describtion");
                LblInstructorInfo3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                LblInstructorInfo3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

                describtionField.setText("jTextField1");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(LblInstructorInfo,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                324,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(330, 330, 330))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(LblInstructorInfo3)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(describtionField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                371,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(titleField,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                371,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(311, 311,
                                                                                                                                311))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(LblInstructorInfo1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                46,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(318, 318, 318)
                                                                .addComponent(btnSave)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnReturn)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel1,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                76,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(LblInstructorInfo,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(LblInstructorInfo1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                33,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(titleField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                28,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(LblInstructorInfo3)
                                                                                .addComponent(describtionField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                28,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                25,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(btnSave)
                                                                                .addComponent(btnReturn))
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                494,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                                "save changes?",
                                "Confirm save", javax.swing.JOptionPane.YES_NO_OPTION);

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        if (titleField.getText().isEmpty() || describtionField.getText().isEmpty()) {
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "cannot save empty course.",
                                                "No data", javax.swing.JOptionPane.WARNING_MESSAGE);
                                return;
                        }
                        if (mode.equalsIgnoreCase("create")) {
                                course.setTitle(titleField.getText());
                                course.setDescription(describtionField.getText());
                                Cdb.update(course);
                                instructor.addCreatedCourse(courseId);
                                Cdb.SaveCoursesToFile();
                                // Refresh parent table
                                if (parentView != null) {
                                        parentView.initializeTableAndLoadData();
                                }
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Now we are ready to add lessons.",
                                                "add lessons", javax.swing.JOptionPane.WARNING_MESSAGE);
                                ViewLessons frame = new ViewLessons(courseId, parentView);
                                frame.setVisible(true);
                                frame.setLocationRelativeTo(null);
                                this.dispose();
                        } else {
                                course.setTitle(titleField.getText());
                                course.setDescription(describtionField.getText());
                                Cdb.update(course);
                                Cdb.SaveCoursesToFile();
                                // Refresh parent table
                                if (parentView != null) {
                                        parentView.initializeTableAndLoadData();
                                }
                                javax.swing.JOptionPane.showMessageDialog(this,
                                                "Now we are ready to edit lessons.",
                                                "edit lessons", javax.swing.JOptionPane.WARNING_MESSAGE);
                                ViewLessons frame = new ViewLessons(courseId, parentView);
                                frame.setVisible(true);
                                frame.setLocationRelativeTo(null);
                                this.dispose();
                        }
                }
        }// GEN-LAST:event_btnSaveActionPerformed

        private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                                "Return without saving changes?",
                                "Confirm return", javax.swing.JOptionPane.YES_NO_OPTION);

                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                        this.dispose();
                }
        }// GEN-LAST:event_btnReturnActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(CourseEditor.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(CourseEditor.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(CourseEditor.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(CourseEditor.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel LblInstructorInfo;
        private javax.swing.JLabel LblInstructorInfo1;
        private javax.swing.JLabel LblInstructorInfo3;
        private javax.swing.JButton btnReturn;
        private javax.swing.JButton btnSave;
        private javax.swing.JTextField describtionField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField titleField;
        // End of variables declaration//GEN-END:variables
}
