package frontend.Instructor;

import java.util.ArrayList;

import javax.swing.JDialog;

import backend.models.*;
import backend.models.Student.studentCourseInfo;
import frontend.util.ProgressBarRenderer;
import backend.databaseManager.*;

/**
 *
 * @author pc
 */
public class EnrolledStudents extends javax.swing.JDialog {

    String courseId;
    Course course;
    ArrayList<Student> students;
    CourseDatabaseManager Cdb;
    UsersDatabaseManager Udb;
    private javax.swing.table.DefaultTableModel studentsModel;

    /**
     * Creates new form EnrolledStudents
     */
    public EnrolledStudents(String courseId, InstructorDashboard parent) {
        super(parent, "Dialog", true);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(parent);
        this.courseId = courseId;
        Cdb = new CourseDatabaseManager();
        Udb = new UsersDatabaseManager();
        course = Cdb.getCourse(courseId);
        students = new ArrayList<Student>();
        initComponents();
        try {
            advancedInitialize();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error : could not load enrolled students");
        }
    }

    private void advancedInitialize() {
        Student s;
        LblEnrolledStudentsInfo.setText("Students of Course: " +
                course.getTitle() + " (ID: " + courseId + ")");

        // populate enrolled students arraylist
        ArrayList<String> studentIDs = course.getStudents();
        for (int i = 0; i < studentIDs.size(); i++) {
            s = (Student) Udb.getUser(studentIDs.get(i));
            students.add(s);
        }

        // Initiating table model
        studentsModel = new javax.swing.table.DefaultTableModel(
                new Object[][] {}, // Empty data initially
                new String[] { "Student ID", "Username", "Email", "Progress" } // Column names
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Make all cells non-editable
                return false;
            }
        };
        tableEnrolledStudents.setModel(studentsModel);
        tableEnrolledStudents.getColumnModel().getColumn(3).setCellRenderer(new ProgressBarRenderer());

        // Populate table
        for (int i = 0; i < students.size(); i++) {
            //!NTST
            s = students.get(i);
            int numCompleted = s.getEnrolledCourses().get(courseId).getProgress().size();
            int numLessons = course.getLessons().size();
            int percentage = numLessons == 0 ? 0 : (numCompleted * 100) / numLessons;
            studentsModel.addRow(new Object[] {
                    s.getUserId(), s.getUsername(),
                    s.getEmail(), percentage
            });
        }
        System.out.println("Students table loaded , size: " + students.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableEnrolledStudents = new javax.swing.JTable();
        LblEnrolledStudentsInfo = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableEnrolledStudents.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Student ID", "Username", "Email", "progress"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableEnrolledStudents);

        LblEnrolledStudentsInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblEnrolledStudentsInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblEnrolledStudentsInfo.setText("jLabel2");
        LblEnrolledStudentsInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblEnrolledStudentsInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReturn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LblEnrolledStudentsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 604,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnReturn)
                                .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 598,
                                                Short.MAX_VALUE)
                                        .addContainerGap())));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LblEnrolledStudentsInfo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(528, 528, 528)
                                .addComponent(btnReturn)
                                .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(41, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnReturnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblEnrolledStudentsInfo;
    private javax.swing.JButton btnReturn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableEnrolledStudents;
    // End of variables declaration//GEN-END:variables
}
