package frontend.Instructor;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import frontend.Login;

/**
 *
 * @author pc
 */
public class InstructorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form InstructorDashboard
     */
    public InstructorDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblInstructorInfo = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        myCoursesTable = new javax.swing.JTable();
        btnCreateCourse = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnViewStudents = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnViewLessons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Instructor Dashboard");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LblInstructorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblInstructorInfo.setText("jLabel2");
        LblInstructorInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh Data");
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRefresh.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        myCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Course ID", "Title", "Description", "Students Enrolled"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(myCoursesTable);

        btnCreateCourse.setBackground(new java.awt.Color(0, 204, 0));
        btnCreateCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateCourse.setText("Create new Course");
        btnCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCourseActionPerformed(evt);
            }
        });

        btnEditCourse.setBackground(new java.awt.Color(255, 204, 0));
        btnEditCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourse.setText("Edit Course");
        btnEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCourseActionPerformed(evt);
            }
        });

        btnViewStudents.setBackground(new java.awt.Color(0, 102, 204));
        btnViewStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStudents.setText("View Students");
        btnViewStudents.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnViewStudents.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnViewStudents.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentsActionPerformed(evt);
            }
        });

        btnDeleteCourse.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCourse.setText("Delete Course");
        btnDeleteCourse.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDeleteCourse.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDeleteCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnViewLessons.setBackground(new java.awt.Color(153, 0, 153));
        btnViewLessons.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewLessons.setForeground(new java.awt.Color(255, 255, 255));
        btnViewLessons.setText("View Lessons");
        btnViewLessons.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnViewLessons.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnViewLessons.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnViewLessons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLessonsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCreateCourse)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditCourse)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteCourse)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewStudents)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewLessons)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnCreateCourse)
                                                .addComponent(btnEditCourse))
                                        .addComponent(btnViewStudents)
                                        .addComponent(btnDeleteCourse)
                                        .addComponent(btnViewLessons))
                                .addGap(12, 12, 12)));

        jTabbedPane2.addTab("My Courses", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LblInstructorInfo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        479, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnRefresh,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(btnLogout))
                                                        .addComponent(jTabbedPane2,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addContainerGap()))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42,
                                                Short.MAX_VALUE)
                                        .addComponent(LblInstructorInfo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?",
                "Confirm Logout", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Suggested function: AuthService.logout(currentStudentId)
            Login frame = new Login();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);

            // Close the dashboard
            this.dispose();

            // Show success message
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Logged out successfully!",
                    "Logout", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        }
    }// GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateCourseActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCreateCourseActionPerformed

    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditCourseActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEditCourseActionPerformed

    private void btnViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnViewStudentsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnViewStudentsActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnDeleteCourseActionPerformed

    private void btnViewLessonsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnViewLessonsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnViewLessonsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblInstructorInfo;
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewLessons;
    private javax.swing.JButton btnViewStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable myCoursesTable;
    // End of variables declaration//GEN-END:variables
}
