package frontend.Instructor;

import javax.swing.JDialog;
import javax.swing.JFrame;

import backend.databaseManager.CourseDatabaseManager;
import backend.models.*;

/**
 *
 * @author pc
 */
public class LessonEditor extends javax.swing.JDialog {
    String mode;
    String courseId;
    String lessonId;
    Lesson lesson;
    Course course;
    CourseDatabaseManager Cdb;
    private ViewLessons parentView;

    /**
     * Creates new form LessonEditor
     */
    public LessonEditor(String courseId, ViewLessons parent) {
        // !NTST
        super(parent, "Dialog", true);
        this.parentView = parent; // Store reference to parent
        this.mode = "create";
        this.courseId = courseId;
        Cdb = new CourseDatabaseManager();
        course = Cdb.getCourse(courseId);
        initComponents();
        advancedIntialize();
        this.lessonId = "";
        lesson = new Lesson(course.generateLessonId(), "", courseId, "");
    }

    public LessonEditor(String courseId, String lessonId, ViewLessons parent) {
        // !NTST
        super(parent, "Dialog", true);
        this.parentView = parent; // Store reference to parent
        this.mode = "edit";
        this.courseId = courseId;
        this.lessonId = lessonId;
        Cdb = new CourseDatabaseManager();
        course = Cdb.getCourse(courseId);
        for (int i = 0; i < course.getLessons().size(); i++) {
            if (lessonId.equals(course.getLessons().get(i).getLessonId())) {
                lesson = course.getLessons().get(i);
                break;
            }
        }
        initComponents();
        advancedIntialize();
    }

    private void advancedIntialize() {
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        String title;
        String content;
        if (mode.equalsIgnoreCase("create")) {
            title = "";
            content = "";
            LblInstructorInfo.setText("");
        } else {
            title = lesson.getTitle();
            content = lesson.getContent();
            LblInstructorInfo.setText("Lesson: " + title + " (ID: " + lessonId + ")");
        }
        titlefield.setText(title);
        contentField.setText(content);
        resourceField.setText("");
        // Name of label is not meaningful , but irrelevant here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblInstructorInfo = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        titlefield = new javax.swing.JTextField();
        btnAddResource = new javax.swing.JButton();
        LblInstructorInfo1 = new javax.swing.JLabel();
        LblInstructorInfo2 = new javax.swing.JLabel();
        LblInstructorInfo3 = new javax.swing.JLabel();
        contentField = new javax.swing.JTextField();
        resourceField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lesson Edit");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LblInstructorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblInstructorInfo.setText("jLabel2");
        LblInstructorInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.setToolTipText("");
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReturn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 204, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        titlefield.setText("jTextField1");

        btnAddResource.setBackground(new java.awt.Color(0, 51, 255));
        btnAddResource.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddResource.setForeground(new java.awt.Color(255, 255, 255));
        btnAddResource.setText("add Resource");
        btnAddResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddResourceActionPerformed(evt);
            }
        });

        LblInstructorInfo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo1.setText("Title");
        LblInstructorInfo1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LblInstructorInfo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblInstructorInfo2.setText("Optional Resources");
        LblInstructorInfo2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LblInstructorInfo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblInstructorInfo3.setText("Content");
        LblInstructorInfo3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        contentField.setText("jTextField1");

        resourceField.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(312, 312, 312)
                                                .addComponent(btnSave)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnReturn))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnAddResource)
                                                        .addGroup(jPanel1Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel1)
                                                                        .addGap(11, 11, 11)
                                                                        .addComponent(LblInstructorInfo,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(6, 6, 6)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(LblInstructorInfo3)
                                                                                .addComponent(LblInstructorInfo1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        46,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(19, 19, 19)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(contentField,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        370, Short.MAX_VALUE)
                                                                                .addComponent(titlefield)))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(LblInstructorInfo2)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(resourceField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                290,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 9, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76,
                                                                Short.MAX_VALUE)
                                                        .addComponent(LblInstructorInfo,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LblInstructorInfo1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        36, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(titlefield, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LblInstructorInfo3)
                                        .addComponent(contentField, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(LblInstructorInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resourceField, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddResource)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSave)
                                        .addComponent(btnReturn))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Return without saving changes?",
                "Confirm return", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }// GEN-LAST:event_btnReturnActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "save changes?",
                "Confirm save", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            if (titlefield.getText().isEmpty() || contentField.getText().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "cannot save empty lesson.",
                        "No data", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (mode.equalsIgnoreCase("create")) {
                lesson.setTitle(titlefield.getText());
                lesson.setContent(contentField.getText());
                course.addLesson(lesson);
                Cdb.update(course);
                Cdb.SaveCoursesToFile();
                // Refresh parent table
                if (parentView != null) {
                    parentView.initializeTableAndLoadData();
                }
                this.dispose();
            } else {
                lesson.setTitle(titlefield.getText());
                lesson.setContent(contentField.getText());
                course.editLesson(lessonId, lesson);
                Cdb.update(course);
                Cdb.SaveCoursesToFile();
                // Refresh parent table
                if (parentView != null) {
                    parentView.initializeTableAndLoadData();
                }
                this.dispose();
            }
        }
    }// GEN-LAST:event_btnSaveActionPerformed

    private void btnAddResourceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddResourceActionPerformed
        String resource = resourceField.getText();
        // input is present
        if (resource.length() > 0 && titlefield.getText().length() > 0
                && contentField.getText().length() > 0) {
            lesson.addResource(resource);
            resourceField.setText("");
        } else if (resource.length() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "cannot empty resources to lesson.",
                    "No data", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "cannot add resources to empty lesson.",
                    "No data", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    }// GEN-LAST:event_btnAddResourceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonEditor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonEditor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonEditor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonEditor.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new LessonEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblInstructorInfo;
    private javax.swing.JLabel LblInstructorInfo1;
    private javax.swing.JLabel LblInstructorInfo2;
    private javax.swing.JLabel LblInstructorInfo3;
    private javax.swing.JButton btnAddResource;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField contentField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resourceField;
    private javax.swing.JTextField titlefield;
    // End of variables declaration//GEN-END:variables
}
