package frontend.Instructor;

import java.util.ArrayList;

import javax.swing.JDialog;
import javax.swing.JFrame;

import backend.models.*;
import backend.databaseManager.*;

/**
 *
 * @author pc
 */

public class ViewLessons extends JFrame {
    String courseId;
    String Title;
    CourseDatabaseManager Cdb;
    ArrayList<Lesson> lessons;
    private javax.swing.table.DefaultTableModel lessonsModel;

    /**
     * Creates new form ViewLessons
     */
    public ViewLessons(String courseId) {

        this.courseId = courseId;
        this.Title = "";
        //name of label is not right 
        Cdb = new CourseDatabaseManager();
        initComponents();
        initializeTableAndLoadData();
        LblInstructorInfo.setText("Lessons of Course: " + Title + " (ID: " + courseId + ")");
    }

    public void initializeTableAndLoadData() {
        Title = Cdb.getCourse(courseId).getTitle();
        this.lessons = Cdb.getCourse(courseId).getLessons();
        if (this.lessons == null) {
            this.lessons = new ArrayList<Lesson>();
        }
        lessonsModel = new javax.swing.table.DefaultTableModel(
                new Object[][] {}, // Empty data initially
                new String[] { "Lesson ID", "Title", "Content" } // Column names
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Make all cells non-editable
                return false;
            }
        };
        lessonsTable.setModel(lessonsModel);
        for (int i = 0; i < lessons.size(); i++) {
            Lesson l = lessons.get(i);
            lessonsModel.addRow(new Object[] {
                    l.getLessonId(), l.getTitle(),
                    l.getContent()
            });
        }
        System.out.println("lesson table loaded , size: " + lessons.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        LblInstructorInfo = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lessonsTable = new javax.swing.JTable();
        btnCreateLesson = new javax.swing.JButton();
        btnEditLesson = new javax.swing.JButton();
        btnDeleteLesson = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblInstructorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInstructorInfo.setText("jLabel2");
        LblInstructorInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReturn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        lessonsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Lesson ID", "Title", "Content"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(lessonsTable);

        btnCreateLesson.setBackground(new java.awt.Color(0, 204, 0));
        btnCreateLesson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateLesson.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateLesson.setText("Create new Lesson");
        btnCreateLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLessonActionPerformed(evt);
            }
        });

        btnEditLesson.setBackground(new java.awt.Color(255, 204, 0));
        btnEditLesson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditLesson.setForeground(new java.awt.Color(255, 255, 255));
        btnEditLesson.setText("Edit Lesson");
        btnEditLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLessonActionPerformed(evt);
            }
        });

        btnDeleteLesson.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteLesson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteLesson.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLesson.setText("Delete Lesson");
        btnDeleteLesson.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDeleteLesson.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDeleteLesson.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCreateLesson)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditLesson)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteLesson)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnCreateLesson)
                                                .addComponent(btnEditLesson))
                                        .addComponent(btnDeleteLesson))
                                .addGap(12, 12, 12)));

        jTabbedPane2.addTab("lessons", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(btnReturn))
                                                        .addComponent(jTabbedPane2,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 469,
                                                                Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addComponent(LblInstructorInfo, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LblInstructorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReturn)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
        this.dispose();
    }// GEN-LAST:event_btnReturnActionPerformed

    private void btnCreateLessonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateLessonActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Add Lesson ?",
                "Confirm addition", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            JDialog frame = new LessonEditor(courseId, this);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            frame.setLocationRelativeTo(null);
        }
        //wait for child to finish
        try {
            initializeTableAndLoadData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_btnCreateLessonActionPerformed

    private void btnEditLessonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditLessonActionPerformed
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a lesson to edit.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = (String) lessonsTable.getValueAt(selectedRow, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Edit Lesson: " + lessonsTable.getValueAt(selectedRow, 1) + "?",
                "Confirm Edit", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            JDialog frame = new LessonEditor(courseId,id,this);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            frame.setLocationRelativeTo(null);
        }
        try {
            initializeTableAndLoadData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_btnEditLessonActionPerformed

    private void btnDeleteLessonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteLessonActionPerformed
        int selectedRow = lessonsTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a lesson to delete.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        Course c = (Course) Cdb.getCourse(courseId);
        String id = (String) lessonsTable.getValueAt(selectedRow, 0);
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Delete Lesson: " + lessonsTable.getValueAt(selectedRow, 1) + "?",
                "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            c.removeLesson(id);
            Cdb.update(c);
            Cdb.SaveCoursesToFile();
        }
        try {
            initializeTableAndLoadData();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }// GEN-LAST:event_btnDeleteLessonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLessons.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLessons.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLessons.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLessons.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLessons("C1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblInstructorInfo;
    private javax.swing.JButton btnCreateLesson;
    private javax.swing.JButton btnDeleteLesson;
    private javax.swing.JButton btnEditLesson;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable lessonsTable;
    // End of variables declaration//GEN-END:variables
}
