/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

import backend.models.*;
import backend.databaseManager.*;
import backend.services.*;

import java.util.ArrayList;

/**
 *
 * @author ahmme
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        loadPendingCourses();
        loadAcceptedRejectedCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar2 = new javax.swing.JToolBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2Acceptedorrejected = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Pendingcourses = new javax.swing.JTable();
        btnLogout = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar2.setRollover(true);

        jTable2Acceptedorrejected.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Course ID", "Title", "Description", "Instructor", "Course state"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2Acceptedorrejected);

        jToolBar2.add(jScrollPane2);

        jTabbedPane1.addTab("Accepted and rejected courses", jToolBar2);

        jToolBar1.setRollover(true);

        jTable1Pendingcourses.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Course ID", "Title", "Description", "Instructor", "Course state"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1Pendingcourses);

        jToolBar1.add(jScrollPane1);

        jTabbedPane1.addTab("Pending Courses", jToolBar1);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh Data");
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRefresh.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAccept.setBackground(new java.awt.Color(0, 102, 204));
        btnAccept.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAccept.setForeground(new java.awt.Color(255, 255, 255));
        btnAccept.setText("Accept");
        btnAccept.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAccept.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAccept.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(0, 102, 204));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Reject");
        btnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRemove.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAccept)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnRemove)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23,
                                                        Short.MAX_VALUE)
                                                .addComponent(btnLogout))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                        Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(24, Short.MAX_VALUE)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAccept, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnRemove, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();

    }// GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        loadPendingCourses();
        loadAcceptedRejectedCourses();

    }// GEN-LAST:event_btnRefreshActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAcceptActionPerformed
        int row = jTable1Pendingcourses.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course to accept!");
            return;
        }

        String courseId = jTable1Pendingcourses.getValueAt(row, 0).toString();

        adminService.approveCourse(courseId);

        JOptionPane.showMessageDialog(this, "Course Approved!");

        loadPendingCourses();
        loadAcceptedRejectedCourses();

    }// GEN-LAST:event_btnAcceptActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRemoveActionPerformed
        int row = jTable1Pendingcourses.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a course to reject!");
            return;
        }

        String courseId = jTable1Pendingcourses.getValueAt(row, 0).toString();

        adminService.rejectCourse(courseId);

        JOptionPane.showMessageDialog(this, "Course Rejected!");

        loadPendingCourses();
        loadAcceptedRejectedCourses();

    }// GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1Pendingcourses;
    private javax.swing.JTable jTable2Acceptedorrejected;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
    private AdminService adminService = new AdminService("U9");

    private void loadPendingCourses() {
        DefaultTableModel model = (DefaultTableModel) jTable1Pendingcourses.getModel();
        model.setRowCount(0);

        for (Course c : adminService.getPendingCourses()) {
            model.addRow(new Object[] {
                    c.getCourseId(),
                    c.getTitle(),
                    c.getDescription(),
                    c.getInstructorId(),
                    c.getApprovalStatus()
            });
        }
    }

    private void loadAcceptedRejectedCourses() {
        DefaultTableModel model = (DefaultTableModel) jTable2Acceptedorrejected.getModel();
        model.setRowCount(0);

        ArrayList<Course> all = new ArrayList<>();
        all = adminService.getApprovedCourses();

        // // Fetch all rejected courses too
        // CourseDatabaseManager db = new CourseDatabaseManager();
        // JSONArray arr = db.getAllCourses();
        // for (int i = 0; i < arr.length(); i++) {
        //     String id = arr.getJSONObject(i).getString("courseId");
        //     Course c = db.getCourseWithoutLessons(id);
        //     if (c.getApprovalStatus().equals("REJECTED")) {
        //         all.add(c);
        //     }
        // }

        for (Course c : all) {
            model.addRow(new Object[] {
                    c.getCourseId(),
                    c.getTitle(),
                    c.getDescription(),
                    c.getInstructorId(),
                    c.getApprovalStatus()
            });
        }
    }
}
