package frontend;

import java.util.ArrayList;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.UIManager;

import backend.models.Course;
import backend.models.Lesson;
import backend.services.InstructorService;


/**
 * Instructor Dashboard - Skill Forge System
 * Provides instructor functionality for:
 * - Course creation and management
 * - Lesson management (add/edit/delete)
 * - Viewing enrolled students
 * - Course editing and deletion
 */
public class InstructorDashboard extends javax.swing.JFrame {

    // Current instructor information
    private String currentInstructorId;
    private String currentInstructorName;
    private InstructorService IS;

    // Table models for dynamic data
    private javax.swing.table.DefaultTableModel createdCoursesModel;
    private javax.swing.table.DefaultTableModel courseStudentsModel;
    private javax.swing.table.DefaultTableModel courseLessonsModel;

    /**
     * Creates new form InstructorDashboard
     * Enhanced constructor to accept instructor information
     */
    public InstructorDashboard(String instructorId, String instructorName) {
        this.currentInstructorId = instructorId;
        this.currentInstructorName = instructorName;
        IS = new InstructorService(instructorId);
        initComponents();
        initializeEnhancedFeatures();
    }

    /**
     * ========================================================================
     * ENHANCED INITIALIZATION METHOD
     * Initializes additional features beyond basic GUI setup
     * ========================================================================
     */
    private void initializeEnhancedFeatures() {
        // Set instructor information in the label
        LblInstructorInfo.setText("Welcome, " + currentInstructorName + " (ID: " + currentInstructorId + ")");

        // Initialize table models with proper column definitions
        initializeTableModels();

        // Load initial instructor data
        loadInstructorData();
    }

    /**
     * ========================================================================
     * INITIALIZE CUSTOM TABLE MODELS
     * Creates proper table models with correct column structure
     * ========================================================================
     */
    private void initializeTableModels() {
        // Created courses table model
        createdCoursesModel = new javax.swing.table.DefaultTableModel(
                new Object[][] {}, // Empty data initially
                new String[] { "Course ID", "Title", "Description", "Students Enrolled" } // Column names
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Make all cells non-editable
                return false;
            }
        };
        tblCreatedCourses.setModel(createdCoursesModel);

        // Course students table model
        courseStudentsModel = new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "Student ID", "Student Name", "Email", "Progress" }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCourseStudents.setModel(courseStudentsModel);

        // Course lessons table model
        courseLessonsModel = new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "Lesson ID", "Title", "Content" }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCourseLessons.setModel(courseLessonsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblInstructorInfo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCreatedCourses = new javax.swing.JTable();
        btnCreateCourse = new javax.swing.JButton();
        btnEditCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        btnViewStudents = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseStudents = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCourseLessons = new javax.swing.JTable();
        btnAddLesson = new javax.swing.JButton();
        btnEditLesson = new javax.swing.JButton();
        btnDeleteLesson = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Skill Forge - Instructor Dashboard");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Instructor Dashboard");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        LblInstructorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblInstructorInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LblInstructorInfo.setText("jLabel2");
        LblInstructorInfo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        LblInstructorInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblCreatedCourses.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Course ID", "Title", "Description", "Students Enrolled", "Status"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCreatedCourses);

        btnCreateCourse.setBackground(new java.awt.Color(0, 102, 204));
        btnCreateCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateCourse.setText("Create New Course");
        btnCreateCourse.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCreateCourse.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCreateCourse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCourseActionPerformed(evt);
            }
        });

        btnEditCourse.setBackground(new java.awt.Color(255, 153, 0));
        btnEditCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourse.setText("Edit Course");
        btnEditCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteCourse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCourse.setText("Delete Course");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });

        btnViewStudents.setBackground(new java.awt.Color(0, 153, 76));
        btnViewStudents.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStudents.setText("View Students");
        btnViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 153,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewStudents)
                                .addGap(0, 0, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCreateCourse)
                                        .addComponent(btnEditCourse)
                                        .addComponent(btnDeleteCourse)
                                        .addComponent(btnViewStudents))
                                .addGap(12, 12, 12)));

        jTabbedPane1.addTab("My Courses", jPanel2);

        tblCourseStudents.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Student ID", "Student Name", "Email", "Enrollment Date", "Progress"
                }));
        jScrollPane2.setViewportView(tblCourseStudents);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Enrolled Students");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 800,
                                                Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Course Students", jPanel3);

        tblCourseLessons.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Lesson ID", "Title", "Content", "Resources", "Order"
                }));
        jScrollPane3.setViewportView(tblCourseLessons);

        btnAddLesson.setBackground(new java.awt.Color(0, 102, 204));
        btnAddLesson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddLesson.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLesson.setText("Add Lesson");
        btnAddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLessonActionPerformed(evt);
            }
        });

        btnEditLesson.setBackground(new java.awt.Color(255, 153, 0));
        btnEditLesson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditLesson.setForeground(new java.awt.Color(255, 255, 255));
        btnEditLesson.setText("Edit Lesson");
        btnEditLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLessonActionPerformed(evt);
            }
        });

        btnDeleteLesson.setBackground(new java.awt.Color(204, 0, 0));
        btnDeleteLesson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteLesson.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLesson.setText("Delete Lesson");
        btnDeleteLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLessonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Course Lessons");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 800,
                                                Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnAddLesson)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEditLesson)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDeleteLesson)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddLesson)
                                        .addComponent(btnEditLesson)
                                        .addComponent(btnDeleteLesson))
                                .addContainerGap()));

        jTabbedPane1.addTab("Manage Lessons", jPanel4);

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("Refresh Data");
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRefresh.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTabbedPane1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 131,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLogout))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LblInstructorInfo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39,
                                                Short.MAX_VALUE)
                                        .addComponent(LblInstructorInfo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTabbedPane1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnLogout)
                                        .addComponent(btnRefresh))
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ========================================================================
     * REFRESH BUTTON ACTION
     * Reloads all instructor data from the backend
     * API INTEGRATION POINT:
     * InstructorService.getInstructorDashboardData(instructorId)
     * ========================================================================
     */
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefreshActionPerformed
        // Clear existing data from tables
        createdCoursesModel.setRowCount(0);
        courseStudentsModel.setRowCount(0);
        courseLessonsModel.setRowCount(0);

        // TODO: Implement API call to refresh all instructor data
        /*
         * try {
         * // Suggested API function:
         * InstructorService.getInstructorDashboardData(currentInstructorId)
         * // InstructorDashboardData data =
         * InstructorService.getInstructorDashboardData(currentInstructorId);
         * // populateCreatedCoursesTable(data.getCreatedCourses());
         * } catch (Exception e) {
         * javax.swing.JOptionPane.showMessageDialog(this,
         * "Error refreshing data: " + e.getMessage(),
         * "Refresh Error", javax.swing.JOptionPane.ERROR_MESSAGE);
         * return;
         * }
         */

        // Temporary: Reload mock data
        loadInstructorData();

        javax.swing.JOptionPane.showMessageDialog(this,
                "Data refreshed successfully!",
                "Refresh Complete", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnRefreshActionPerformed

    /**
     * ========================================================================
     * LOGOUT BUTTON ACTION
     * Logs out the instructor and returns to login screen
     * API INTEGRATION POINT: AuthService.logout(instructorId)
     * ========================================================================
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?",
                "Confirm Logout", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // TODO: Implement API call for logout
            // Suggested function: AuthService.logout(currentInstructorId)

            // Perform cleanup before exit
            performCleanup();

            // Close the dashboard
            this.dispose();

            // Show success message
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Logged out successfully!",
                    "Logout", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // TODO: Return to login screen
            // new LoginFrame().setVisible(true);
        }
    }// GEN-LAST:event_btnLogoutActionPerformed

    /**
     * ========================================================================
     * CREATE COURSE BUTTON ACTION
     * Opens dialog or form to create a new course
     * API INTEGRATION POINT: CourseService.createCourse(courseData, instructorId)
     * ========================================================================
     */
    private void btnCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCreateCourseActionPerformed
        // TODO: Open course creation dialog/form
        /*
         * CreateCourseDialog dialog = new CreateCourseDialog(this, true,
         * currentInstructorId);
         * dialog.setVisible(true);
         * 
         * if (dialog.isSuccess()) {
         * // Refresh courses list
         * btnRefreshActionPerformed(evt);
         * }
         */

        // Temporary success message for demonstration
        javax.swing.JOptionPane.showMessageDialog(this,
                "Course creation feature would open here.\n\n" +
                        "API Integration Point: CourseService.createCourse(courseData, instructorId)",
                "Create Course", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnCreateCourseActionPerformed

    /**
     * ========================================================================
     * EDIT COURSE BUTTON ACTION
     * Opens dialog to edit selected course
     * API INTEGRATION POINT: CourseService.updateCourse(courseId, courseData)
     * ========================================================================
     */
    private void btnEditCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditCourseActionPerformed
        int selectedRow = tblCreatedCourses.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a course to edit.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) createdCoursesModel.getValueAt(selectedRow, 0);
        String courseTitle = (String) createdCoursesModel.getValueAt(selectedRow, 1);

        // TODO: Open course editing dialog/form
        /*
         * EditCourseDialog dialog = new EditCourseDialog(this, true, courseId);
         * dialog.setVisible(true);
         * 
         * if (dialog.isSuccess()) {
         * // Refresh courses list
         * btnRefreshActionPerformed(evt);
         * }
         */

        // Temporary message for demonstration
        javax.swing.JOptionPane.showMessageDialog(this,
                "Would edit course: " + courseTitle + " (ID: " + courseId + ")\n\n" +
                        "API Integration Point: CourseService.updateCourse(courseId, courseData)",
                "Edit Course", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnEditCourseActionPerformed

    /**
     * ========================================================================
     * DELETE COURSE BUTTON ACTION
     * Deletes the selected course after confirmation
     * API INTEGRATION POINT: CourseService.deleteCourse(courseId)
     * ========================================================================
     */
    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteCourseActionPerformed
        int selectedRow = tblCreatedCourses.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a course to delete.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) createdCoursesModel.getValueAt(selectedRow, 0);
        String courseTitle = (String) createdCoursesModel.getValueAt(selectedRow, 1);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the course:\n" + courseTitle + " (ID: " + courseId + ")?\n\n" +
                        "This action cannot be undone!",
                "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // TODO: Implement API call to delete course
            // Suggested function: CourseService.deleteCourse(courseId)
            /*
             * try {
             * boolean success = CourseService.deleteCourse(courseId);
             * if (success) {
             * javax.swing.JOptionPane.showMessageDialog(this,
             * "Course deleted successfully!",
             * "Delete Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
             * // Refresh courses list
             * btnRefreshActionPerformed(evt);
             * } else {
             * javax.swing.JOptionPane.showMessageDialog(this,
             * "Failed to delete course. Please try again.",
             * "Delete Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
             * }
             * } catch (Exception e) {
             * javax.swing.JOptionPane.showMessageDialog(this,
             * "Delete error: " + e.getMessage(),
             * "API Error", javax.swing.JOptionPane.ERROR_MESSAGE);
             * }
             */

            // Temporary success message for demonstration
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Course would be deleted: " + courseTitle + "\n\n" +
                            "API Integration Point: CourseService.deleteCourse(courseId)",
                    "Delete Course", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_btnDeleteCourseActionPerformed

    /**
     * ========================================================================
     * VIEW STUDENTS BUTTON ACTION
     * Loads and displays students enrolled in the selected course
     * API INTEGRATION POINT: CourseService.getEnrolledStudents(courseId)
     * ========================================================================
     */
    private void btnViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnViewStudentsActionPerformed
        int selectedRow = tblCreatedCourses.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a course to view students.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String courseId = (String) createdCoursesModel.getValueAt(selectedRow, 0);
        String courseTitle = (String) createdCoursesModel.getValueAt(selectedRow, 1);

        // Switch to Course Students tab
        jTabbedPane1.setSelectedIndex(1);

        // TODO: Implement API call to get enrolled students
        // Suggested function: CourseService.getEnrolledStudents(courseId)
        /*
         * try {
         * List<Student> students = CourseService.getEnrolledStudents(courseId);
         * populateCourseStudentsTable(students);
         * } catch (Exception e) {
         * javax.swing.JOptionPane.showMessageDialog(this,
         * "Error loading students: " + e.getMessage(),
         * "Load Error", javax.swing.JOptionPane.ERROR_MESSAGE);
         * }
         */

        // Load mock students for demonstration
        loadMockStudents(courseId, courseTitle);
    }// GEN-LAST:event_btnViewStudentsActionPerformed

    /**
     * ========================================================================
     * ADD LESSON BUTTON ACTION
     * Opens dialog to add a new lesson to the selected course
     * API INTEGRATION POINT: LessonService.addLesson(courseId, lessonData)
     * ========================================================================
     */
    private void btnAddLessonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddLessonActionPerformed
        // Check if a course is selected (you might want to track the current course)
        String currentCourseId = getCurrentSelectedCourseId();
        if (currentCourseId == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a course first from 'My Courses' tab.",
                    "No Course Selected", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // TODO: Open lesson creation dialog
        /*
         * AddLessonDialog dialog = new AddLessonDialog(this, true, currentCourseId);
         * dialog.setVisible(true);
         * 
         * if (dialog.isSuccess()) {
         * // Refresh lessons list
         * loadCourseLessons(currentCourseId);
         * }
         */

        // Temporary message for demonstration
        javax.swing.JOptionPane.showMessageDialog(this,
                "Would add new lesson to course: " + currentCourseId + "\n\n" +
                        "API Integration Point: LessonService.addLesson(courseId, lessonData)",
                "Add Lesson", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnAddLessonActionPerformed

    /**
     * ========================================================================
     * EDIT LESSON BUTTON ACTION
     * Opens dialog to edit selected lesson
     * API INTEGRATION POINT: LessonService.updateLesson(lessonId, lessonData)
     * ========================================================================
     */
    private void btnEditLessonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditLessonActionPerformed
        int selectedRow = tblCourseLessons.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a lesson to edit.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String lessonId = (String) courseLessonsModel.getValueAt(selectedRow, 0);
        String lessonTitle = (String) courseLessonsModel.getValueAt(selectedRow, 1);

        // TODO: Open lesson editing dialog
        /*
         * EditLessonDialog dialog = new EditLessonDialog(this, true, lessonId);
         * dialog.setVisible(true);
         * 
         * if (dialog.isSuccess()) {
         * // Refresh lessons list
         * loadCourseLessons(getCurrentSelectedCourseId());
         * }
         */

        // Temporary message for demonstration
        javax.swing.JOptionPane.showMessageDialog(this,
                "Would edit lesson: " + lessonTitle + " (ID: " + lessonId + ")\n\n" +
                        "API Integration Point: LessonService.updateLesson(lessonId, lessonData)",
                "Edit Lesson", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }// GEN-LAST:event_btnEditLessonActionPerformed

    /**
     * ========================================================================
     * DELETE LESSON BUTTON ACTION
     * Deletes the selected lesson after confirmation
     * API INTEGRATION POINT: LessonService.deleteLesson(lessonId)
     * ========================================================================
     */
    private void btnDeleteLessonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteLessonActionPerformed
        int selectedRow = tblCourseLessons.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a lesson to delete.",
                    "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String lessonId = (String) courseLessonsModel.getValueAt(selectedRow, 0);
        String lessonTitle = (String) courseLessonsModel.getValueAt(selectedRow, 1);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the lesson:\n" + lessonTitle + " (ID: " + lessonId + ")?\n\n" +
                        "This action cannot be undone!",
                "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // TODO: Implement API call to delete lesson
            // Suggested function: LessonService.deleteLesson(lessonId)
            /*
             * try {
             * boolean success = LessonService.deleteLesson(lessonId);
             * if (success) {
             * javax.swing.JOptionPane.showMessageDialog(this,
             * "Lesson deleted successfully!",
             * "Delete Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
             * // Refresh lessons list
             * loadCourseLessons(getCurrentSelectedCourseId());
             * }
             * } catch (Exception e) {
             * javax.swing.JOptionPane.showMessageDialog(this,
             * "Delete error: " + e.getMessage(),
             * "API Error", javax.swing.JOptionPane.ERROR_MESSAGE);
             * }
             */

            // Temporary success message for demonstration
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Lesson would be deleted: " + lessonTitle + "\n\n" +
                            "API Integration Point: LessonService.deleteLesson(lessonId)",
                    "Delete Lesson", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }// GEN-LAST:event_btnDeleteLessonActionPerformed

    // ========================================================================
    // DATA MANAGEMENT METHODS
    // ========================================================================

    /**
     * ========================================================================
     * LOAD INSTRUCTOR DATA
     * Loads initial instructor data including created courses
     * API INTEGRATION POINT:
     * InstructorService.getInstructorDashboardData(instructorId)
     * ========================================================================
     */
    private void loadInstructorData() {
        ArrayList<Course> createdCourses = IS.getCreatedCourses(); 
        for (int i = 0; i < createdCourses.size(); i++) {
            Course c = createdCourses.get(i);
            createdCoursesModel.addRow(new Object[] {
                    c.getCourseId(), c.getTitle(),
                    c.getDescription(),Integer.toString(c.getStudents().size())
            });
            
        }

    }

    /**
     * ========================================================================
     * GET CURRENT SELECTED COURSE ID
     * Helper method to get the currently selected course ID
     * ========================================================================
     */
    private String getCurrentSelectedCourseId() {
        int selectedRow = tblCreatedCourses.getSelectedRow();
        if (selectedRow >= 0) {
            return (String) createdCoursesModel.getValueAt(selectedRow, 0);
        }
        return null;
    }

    /**
     * ========================================================================
     * PERFORM CLEANUP BEFORE EXIT
     * Saves data, closes connections, etc.
     * ========================================================================
     */
    private void performCleanup() {
        // TODO: Add cleanup operations here
        System.out.println("Performing instructor cleanup before exit...");

        // Example cleanup operations:
        // - Save instructor preferences/settings
        // - Close database connections
        // - Log logout event

        System.out.println("Instructor cleanup completed.");
    }


    /**
     * ========================================================================
     * LOAD MOCK STUDENTS FOR DEMONSTRATION
     * Temporary method - Remove when API integration is complete
     * ========================================================================
     */
    private void loadMockStudents(String courseId, String courseTitle) {
        courseStudentsModel.setRowCount(0); // Clear existing students

        // Update the label to show which course we're viewing
        jLabel2.setText("Enrolled Students - " + courseTitle + " (" + courseId + ")");

        // Mock student data
        courseStudentsModel
                .addRow(new Object[] { "STU001", "John Smith", "john.smith@email.com", "2024-01-15", "75%" });
        courseStudentsModel
                .addRow(new Object[] { "STU002", "Alice Johnson", "alice.j@email.com", "2024-01-16", "60%" });
        courseStudentsModel
                .addRow(new Object[] { "STU003", "Bob Wilson", "bob.wilson@email.com", "2024-01-18", "45%" });
        courseStudentsModel.addRow(new Object[] { "STU004", "Carol Davis", "carol.d@email.com", "2024-01-20", "90%" });
        courseStudentsModel.addRow(new Object[] { "STU005", "David Brown", "david.b@email.com", "2024-01-22", "30%" });
    }

    /**
     * ========================================================================
     * LOAD MOCK LESSONS FOR DEMONSTRATION
     * Temporary method - Remove when API integration is complete
     * ========================================================================
     */
    private void loadMockLessons(String courseId) {
        courseLessonsModel.setRowCount(0); // Clear existing lessons

        if ("CS101".equals(courseId)) {
            courseLessonsModel.addRow(new Object[] { "L1", "Introduction to Java", "Basic syntax and structure",
                    "Slides, Code Examples", "1" });
            courseLessonsModel.addRow(new Object[] { "L2", "Variables and Data Types",
                    "Primitive types and declarations", "Slides, Exercises", "2" });
            courseLessonsModel.addRow(new Object[] { "L3", "Control Structures", "If statements and loops",
                    "Slides, Code Examples", "3" });
        } else if ("MATH201".equals(courseId)) {
            courseLessonsModel.addRow(new Object[] { "L1", "Limits and Continuity", "Introduction to calculus limits",
                    "Slides, Practice Problems", "1" });
            courseLessonsModel.addRow(
                    new Object[] { "L2", "Derivatives", "Basic differentiation rules", "Slides, Exercises", "2" });
        }
    }

    /**
     * ========================================================================
     * MAIN METHOD FOR TESTING
     * Enhanced to use the parameterized constructor
     * ========================================================================
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorDashboard.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Use parameterized constructor with instructor data
                new InstructorDashboard("U8", "bebe").setVisible(true);
            }
        });
    }

    // ========================================================================
    // VARIABLE DECLARATIONS - GENERATED BY NETBEANS
    // ========================================================================
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblInstructorInfo;
    private javax.swing.JButton btnAddLesson;
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnDeleteLesson;
    private javax.swing.JButton btnEditCourse;
    private javax.swing.JButton btnEditLesson;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewStudents;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCourseLessons;
    private javax.swing.JTable tblCourseStudents;
    private javax.swing.JTable tblCreatedCourses;
    // End of variables declaration//GEN-END:variables
}